# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67cf0809130279cb47b2fe353f511ceeed090ff7041871974ce6b9a8881d7e852e8d5cd83f46005596dda9a3e9327e61d85b4d8ffe22997f2753806edf49d7ca

test:
  secret_key_base: 82ebada90ecf2e030a376fb3737eef06c8da312249197aeaf6f8a1f44ed9e890b42143f4290769188a2b08a4a8b19256f39e496fc277fe4ea5c48e063f631e5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
